FROM openjdk:8-jdk-alpine
RUN apk add --no-cache openjdk8
MAINTAINER SravanTatikonda
EXPOSE 9901
ARG JAR_FILE=target/dating-main-0.0.1.jar
ADD ${JAR_FILE} dating-main-0.0.1.jar

# ENV rmqHost ec2-18-190-35-204.us-east-2.compute.amazonaws.com
# ENV rmqRelayHost ec2-18-190-35-204.us-east-2.compute.amazonaws.com
# ENV rmqAllowedOrigin ec2-18-190-35-204.us-east-2.compute.amazonaws.com
# ENV rmqUsername rabbitmq
# ENV rmqPassword rabbitmq1234
# ENV rmqSysUsername rabbitmq
# ENV rmqSysPassword rabbitmq1234
# ENV rmqClientUsername rabbitmq
# ENV rmqClientPas rabbitmq1234
ENTRYPOINT ["java", "-jar","/dating-main-0.0.1.jar"]